# RDAP fallback endpoints for TLDs missing from the IANA bootstrap file
# but known to have working RDAP servers.
RDAP_FALLBACK: dict[str, str] = {
    "de": "https://rdap.denic.de/",
    "ch": "https://rdap.nic.ch/",
    "li": "https://rdap.nic.ch/",
    "be": "https://rdap.dns.be/",
    "cz": "https://rdap.nic.cz/",
    "eu": "https://rdap.eurid.eu/",
    "fi": "https://rdap.fi/",
    "hr": "https://rdap.dns.hr/",
    "lv": "https://rdap.nic.lv/",
    "no": "https://rdap.norid.no/",
    "se": "https://rdap.iis.se/",
    "sk": "https://rdap.sk-nic.sk/",
    "si": "https://rdap.register.si/",
}

# WHOIS server overrides: TLD -> (server, query_format)
# query_format uses {domain} as placeholder for the full domain name.
WHOIS_SERVERS: dict[str, tuple[str, str]] = {
    "com": ("whois.verisign-grs.com", "{domain}"),
    "net": ("whois.verisign-grs.com", "{domain}"),
    "org": ("whois.pir.org", "{domain}"),
    "info": ("whois.afilias.net", "{domain}"),
    "biz": ("whois.biz", "{domain}"),
    "name": ("whois.nic.name", "{domain}"),
    "mobi": ("whois.afilias.net", "{domain}"),
    "pro": ("whois.registrypro.pro", "{domain}"),
    "tel": ("whois.nic.tel", "{domain}"),
    "asia": ("whois.nic.asia", "{domain}"),
    "cat": ("whois.nic.cat", "{domain}"),
    "jobs": ("whois.nic.jobs", "{domain}"),
    "travel": ("whois.nic.travel", "{domain}"),
    "coop": ("whois.nic.coop", "{domain}"),
    "museum": ("whois.nic.museum", "{domain}"),
    "aero": ("whois.aero", "{domain}"),
    # ccTLDs
    "ac": ("whois.nic.ac", "{domain}"),
    "ai": ("whois.nic.ai", "{domain}"),
    "am": ("whois.amnic.net", "{domain}"),
    "at": ("whois.nic.at", "{domain}"),
    "au": ("whois.auda.org.au", "{domain}"),
    "be": ("whois.dns.be", "{domain}"),
    "br": ("whois.registro.br", "{domain}"),
    "ca": ("whois.cira.ca", "{domain}"),
    "cc": ("ccwhois.verisign-grs.com", "{domain}"),
    "ch": ("whois.nic.ch", "{domain}"),
    "cl": ("whois.nic.cl", "{domain}"),
    "cn": ("whois.cnnic.cn", "{domain}"),
    "co": ("whois.nic.co", "{domain}"),
    "cx": ("whois.nic.cx", "{domain}"),
    "cz": ("whois.nic.cz", "{domain}"),
    "de": ("whois.denic.de", "-T dn {domain}"),
    "dk": ("whois.punktum.dk", "{domain}"),
    "ee": ("whois.tld.ee", "{domain}"),
    "eu": ("whois.eu", "{domain}"),
    "fi": ("whois.fi", "{domain}"),
    "fr": ("whois.nic.fr", "{domain}"),
    "gg": ("whois.gg", "{domain}"),
    "hk": ("whois.hkirc.hk", "{domain}"),
    "hr": ("whois.dns.hr", "{domain}"),
    "hu": ("whois.nic.hu", "{domain}"),
    "id": ("whois.id", "{domain}"),
    "ie": ("whois.weare.ie", "{domain}"),
    "il": ("whois.isoc.org.il", "{domain}"),
    "in": ("whois.registry.in", "{domain}"),
    "io": ("whois.nic.io", "{domain}"),
    "is": ("whois.isnic.is", "{domain}"),
    "it": ("whois.nic.it", "{domain}"),
    "je": ("whois.je", "{domain}"),
    "jp": ("whois.jprs.jp", "{domain}/e"),
    "ke": ("whois.kenic.or.ke", "{domain}"),
    "kr": ("whois.kr", "{domain}"),
    "li": ("whois.nic.li", "{domain}"),
    "lt": ("whois.domreg.lt", "{domain}"),
    "lu": ("whois.dns.lu", "{domain}"),
    "lv": ("whois.nic.lv", "{domain}"),
    "me": ("whois.nic.me", "{domain}"),
    "mx": ("whois.mx", "{domain}"),
    "my": ("whois.mynic.my", "{domain}"),
    "nl": ("whois.sidn.nl", "{domain}"),
    "no": ("whois.norid.no", "{domain}"),
    "nu": ("whois.iis.nu", "{domain}"),
    "nz": ("whois.srs.net.nz", "{domain}"),
    "pe": ("kero.yachay.pe", "{domain}"),
    "ph": ("whois.dot.ph", "{domain}"),
    "pk": ("whois.pknic.net.pk", "{domain}"),
    "pl": ("whois.dns.pl", "{domain}"),
    "pt": ("whois.dns.pt", "{domain}"),
    "ro": ("whois.rotld.ro", "{domain}"),
    "rs": ("whois.rnids.rs", "{domain}"),
    "ru": ("whois.tcinet.ru", "{domain}"),
    "sa": ("whois.nic.net.sa", "{domain}"),
    "se": ("whois.iis.se", "{domain}"),
    "sg": ("whois.sgnic.sg", "{domain}"),
    "si": ("whois.register.si", "{domain}"),
    "sk": ("whois.sk-nic.sk", "{domain}"),
    "so": ("whois.nic.so", "{domain}"),
    "st": ("whois.nic.st", "{domain}"),
    "su": ("whois.tcinet.ru", "{domain}"),
    "th": ("whois.thnic.co.th", "{domain}"),
    "tk": ("whois.dot.tk", "{domain}"),
    "tr": ("whois.trabis.gov.tr", "{domain}"),
    "tv": ("tvwhois.verisign-grs.com", "{domain}"),
    "tw": ("whois.twnic.net.tw", "{domain}"),
    "ua": ("whois.ua", "{domain}"),
    "uk": ("whois.nic.uk", "{domain}"),
    "us": ("whois.nic.us", "{domain}"),
    "uy": ("whois.nic.org.uy", "{domain}"),
    "uz": ("whois.cctld.uz", "{domain}"),
    "ve": ("whois.nic.ve", "{domain}"),
    "za": ("whois.registry.net.za", "{domain}"),
}

# Patterns indicating a domain is available (checked case-insensitively against WHOIS response)
AVAILABLE_PATTERNS: list[str] = [
    "no match for",
    "not found",
    "no entries found",
    "no data found",
    "status: free",
    "status: available",
    "domain not found",
    "no information available",
    "the queried object does not exist",
    "no object found",
    "is free",
    "no such domain",
    "nothing found",
    "no match",
    "this domain name has not been registered",
    "object does not exist",
    "domain name not known",
    "% no matching objects found",
]

# Patterns indicating WHOIS rate limiting or errors (not availability)
RATE_LIMIT_PATTERNS: list[str] = [
    "rate limit",
    "too many queries",
    "query rate exceeded",
    "try again later",
    "connection limit",
    "quota exceeded",
    "temporarily denied",
]

# Patterns indicating WHOIS privacy/proxy protection (checked case-insensitively)
PRIVACY_PATTERNS: list[str] = [
    "redacted for privacy",
    "data protected",
    "domains by proxy",
    "whoisguard",
    "privacy service provided by",
    "contact privacy inc",
    "withheld for privacy",
    "identity protection service",
    "domain privacy group",
    "whoisprivacyprotect",
    "privacyguardian",
    "perfect privacy",
    "privacy protect",
    "super privacy",
    "domain protection services",
    "statutorily masked",
    "not disclosed",
    "gdpr masked",
    "gdpr redacted",
    "is not shown",
    "personal data not shown",
]

# RDAP bootstrap cache settings
BOOTSTRAP_URL = "https://data.iana.org/rdap/dns.json"
BOOTSTRAP_CACHE_TTL_HOURS = 24

# Network timeouts (seconds)
CONNECT_TIMEOUT = 5
READ_TIMEOUT = 10
